model_name=Uniformer

python -u run.py \
    --task_name long_term_forecast \
    --is_training 1 \
    --root_path ./dataset/solar/ \
    --data_path solar.csv \
    --model_id SOLAR_96_96 \
    --model Uniformer \
    --data custom \
    --features M \
    --seq_len 96  \
    --pred_len 96 \
    --e_layers 1 \
    --n_heads 1 \
    --enc_in 137 \
    --input_dim 1   \
    --node_dim 64 \
    --embed_dim 256 \
    --d_ff 512  \
    --num_layer 1 \
    --des 'Exp' \
    --itr 1  \
    --learning_rate 0.001  \
    --if_node 

python -u run.py \
    --task_name long_term_forecast \
    --is_training 1 \
    --root_path ./dataset/solar/ \
    --data_path solar.csv \
    --model_id SOLAR_96_192 \
    --model Uniformer \
    --data custom \
    --features M \
    --seq_len 96  \
    --pred_len 192 \
    --e_layers 1 \
    --n_heads 1 \
    --enc_in 137 \
    --input_dim 1   \
    --node_dim 64 \
    --embed_dim 256 \
    --d_ff 512  \
    --num_layer 1 \
    --des 'Exp' \
    --itr 1  \
    --learning_rate 0.001  \
    --if_node 

python -u run.py \
    --task_name long_term_forecast \
    --is_training 1 \
    --root_path ./dataset/solar/ \
    --data_path solar.csv \
    --model_id SOLAR_96_336 \
    --model Uniformer \
    --data custom \
    --features M \
    --seq_len 96  \
    --pred_len 336 \
    --e_layers 1 \
    --n_heads 1 \
    --enc_in 137 \
    --input_dim 1   \
    --node_dim 64 \
    --embed_dim 256 \
    --d_ff 512  \
    --num_layer 1 \
    --des 'Exp' \
    --itr 1  \
    --learning_rate 0.001  \
    --if_node 

python -u run.py \
    --task_name long_term_forecast \
    --is_training 1 \
    --root_path ./dataset/solar/ \
    --data_path solar.csv \
    --model_id SOLAR_96_720 \
    --model Uniformer \
    --data custom \
    --features M \
    --seq_len 96  \
    --pred_len 720 \
    --e_layers 1 \
    --n_heads 1 \
    --enc_in 137 \
    --input_dim 1  \
    --node_dim 64 \
    --embed_dim 256 \
    --d_ff 512  \
    --num_layer 1 \
    --des 'Exp' \
    --itr 1  \
    --learning_rate 0.001  \
    --if_node 
